spring:
  config:
    import: classpath:config/application-jwt.yml, classpath:config/application-s3.yml
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 30
        format_sql: true
        jdbc.time_zone: Asia/Seoul
    show-sql: true

server:
  address: 0.0.0.0
  port: 8080
  
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.web.servlet.DispatcherServlet: DEBUG
---

spring:
  config:
    import: classpath:config/application-dev.yml
    activate:
      on-profile: dev

---

spring:
  config:
    import: classpath:config/application-prod.yml
    activate:
      on-profile: prod

---





