name: 1-feature-template
description: 새로운 기능을 추가
title: "feat: Feature Title"
labels: ["✨feat","🛠️BE"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: 💬 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요!
      placeholder: ex. 로그인 기능 추가
    validations:
      required: true
  - type: textarea
    id: feature-contents-detail
    attributes:
      label: 💫 작업 상세 내용
      description: 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
    validations:
      required: false
